Q1. Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans - Yes there is a difference in the data types between list_ and array_list. In Python, list_ is a Python list object, which can contain elements of any type. On the other hand, array_list is a NumPy array object, where all elements are coerced to a common data type during creation.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_: ", type(list_))
print("Data type of array_list: ", array_list.dtype)
print("array_list, Since the elements are strings e.g., '1', '2', the data type here would be '<U1', which means Unicode strings of length 1")

Data type of list_:  <class 'list'>
Data type of array_list:  <U1
array_list. Since the elements are strings (e.g., '1', '2'), the data type here would be '<U1', which means Unicode strings of length 1 (single character strings).


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for i in list_:
    print(type(i))

print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans - Yes there will be a difference in the data types of the elements between list_ and array_list after the change. When creating array_list with dtype=int, NumPy will attempt to convert each element from the list_ (which contains strings) into integers. 

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for i in list_:
    print(type(i))
    
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


a. num_array.shape gives the shape of the array num_array, which is (2, 3), indicating it has 2 rows and 3 columns.

b. num_array.size gives the total number of elements in the array num_array, which is 6 in this case (2 rows * 3 columns).

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [9]:
import numpy as np
data = np.random.randint(0, 1, (3, 3))
print(data)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [10]:
import numpy as np

data1 = np.diag([1, 1, 1, 1, 1])
print(data1)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
